import {expect, test} from '@playwright/test'

test.beforeEach(async ({page}) => {
  await page.goto('/demo')
  await page.evaluate(() => document.fonts.ready)
})

test('accordion exposes one chapter at a time and supports keyboard collapse', async ({page}) => {
  const section = page.locator('#accordion')
  const supplies = section.getByRole('button', {name: 'What should I bring?'})
  const rewards = section.getByRole('button', {name: 'What is the reward?'})
  const supplyText = section.getByText('Pack a lantern, two healing potions, and a spare map.')
  const rewardText = section.getByText('Return the moonstone to earn 120 gold and a ranger badge.')
  await expect(supplyText).toBeVisible()
  await expect(rewardText).toBeHidden()
  await supplies.focus()
  await page.keyboard.press('Tab')
  await expect(rewards).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(rewards).toHaveAttribute('aria-expanded', 'true')
  await expect(supplies).toHaveAttribute('aria-expanded', 'false')
  await expect(supplyText).toBeHidden()
  await expect(rewardText).toBeVisible()
  await expect(section.getByRole('status').filter({hasText: 'Reading rewards.'})).toHaveText('Reading rewards.')
  await page.keyboard.press('Tab')
  const closeAll = section.getByRole('button', {name: 'Close all chapters'})
  await expect(closeAll).toBeFocused()
  await expect(section.getByRole('button', {name: 'The sealed chamber'})).toBeDisabled()
  await page.keyboard.press('Enter')
  await expect(rewardText).toBeHidden()
  await expect(section.getByRole('status').filter({hasText: 'All chapters closed.'})).toHaveText('All chapters closed.')
  await supplies.focus()
  await page.keyboard.press('Space')
  await expect(supplyText).toBeVisible()
  await page.keyboard.press('Space')
  await expect(supplyText).toBeHidden()
})

test('notification supports F6, keyboard dismissal and return to its opener', async ({page}) => {
  const section = page.locator('#toast')
  const save = section.getByRole('button', {name: 'Save quest', exact: true})
  await save.click()
  const dismiss = page.getByRole('button', {name: 'Dismiss notification', exact: true})
  const notification = page.getByRole('status').filter({has: dismiss})
  await expect(notification).toContainText('Quest progress saved. Your camp is ready.')
  await expect(save).toBeFocused()
  await page.keyboard.press('F6')
  await expect(dismiss).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(notification).not.toBeVisible()
  await expect(section.getByRole('status').filter({hasText: 'Notification dismissed.'})).toHaveText('Notification dismissed.')
  await expect(save).toBeFocused()
})

test('reward notification auto-hides after the consumer-configured duration', async ({page}) => {
  await page.locator('#toast').getByRole('button', {name: 'Collect reward'}).click()
  const dismiss = page.getByRole('button', {name: 'Dismiss notification', exact: true})
  const notification = page.getByRole('status').filter({has: dismiss})
  await expect(notification).toContainText('You collected 120 gold.')
  await expect(notification).not.toBeVisible({timeout: 8000})
  await expect(page.locator('#toast').getByRole('status').filter({hasText: 'Notification expired.'})).toHaveText('Notification expired.')
})

test('consumer-owned warning is dismissible and can be shown again', async ({page}) => {
  const section = page.locator('#toast')
  const show = section.getByRole('button', {name: 'Show connection warning'})
  await show.click()
  const warning = section.getByRole('alert')
  await expect(warning).toHaveAttribute('aria-live', 'assertive')
  await expect(warning).toContainText('Connection lost. Your progress is stored locally.')
  await expect(show).toBeDisabled()
  const dismiss = warning.getByRole('button', {name: 'Dismiss connection warning'})
  await dismiss.focus()
  await page.keyboard.press('Space')
  await expect(warning).toHaveCount(0)
  await expect(show).toBeEnabled()
  await show.click()
  await expect(warning).toBeVisible()
})

for (const theme of ['overworld', 'castle'] as const) {
  test(`disclosure and notification framing in ${theme}`, async ({page}) => {
    if (theme === 'castle') await page.getByRole('button', {name: 'Switch to Castle', exact: true}).click()
    await expect(page.locator('#accordion')).toHaveScreenshot(`accordion-${theme}.png`)
    await page.locator('#toast').getByRole('button', {name: 'Save quest', exact: true}).click()
    const notification = page.getByRole('status').filter({has: page.getByRole('button', {name: 'Dismiss notification', exact: true})})
    await expect(notification).toBeVisible()
    await expect(notification).toHaveScreenshot(`toast-${theme}.png`)
    await page.locator('#toast').getByRole('button', {name: 'Show connection warning'}).click()
    await expect(page.locator('#toast').getByRole('alert')).toHaveScreenshot(`toast-error-${theme}.png`)
  })
}

test('disclosure remains usable in forced colors and reduced motion', async ({page}) => {
  await page.emulateMedia({forcedColors: 'active', reducedMotion: 'reduce'})
  const accordion = page.locator('#accordion')
  await accordion.getByRole('button', {name: 'What is the reward?'}).click()
  await expect(accordion.getByText('Return the moonstone to earn 120 gold and a ranger badge.')).toBeVisible()
  await expect(accordion).toHaveScreenshot('accordion-forced-colors.png')
  await page.locator('#toast').getByRole('button', {name: 'Show connection warning'}).click()
  const warning = page.locator('#toast').getByRole('alert')
  await expect(warning).toHaveCSS('transition-duration', '0s')
  await expect(warning).toHaveScreenshot('toast-forced-colors.png')
  await warning.getByRole('button', {name: 'Dismiss connection warning'}).click()
  await expect(warning).toHaveCount(0)
})
