import {expect, test} from '@playwright/test'

test.beforeEach(async ({page}) => {
  await page.goto('/demo')
  await page.evaluate(() => document.fonts.ready)
})

test('tooltip supports hover, focus, Escape and the trigger action', async ({page}) => {
  const section = page.locator('#tooltip')
  const trigger = section.getByRole('button', {name: 'Drink potion'})
  await trigger.hover()
  const tooltip = page.getByRole('tooltip')
  await expect(tooltip).toHaveText('Restores 20 health. Save one for the boss.')
  await expect(tooltip).toHaveScreenshot('quest-tooltip.png')
  await section.getByRole('heading').hover()
  await expect(tooltip).not.toBeVisible()
  await trigger.focus()
  await expect(tooltip).toBeVisible()
  await expect(trigger).toHaveAccessibleDescription('Restores 20 health. Save one for the boss.')
  await page.keyboard.press('Escape')
  await expect(tooltip).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(section.getByRole('status').filter({hasText: 'potions remaining'})).toHaveText('2 potions remaining')
  await page.keyboard.press('Tab')
  await expect(tooltip).not.toBeVisible()
})

test('progress advances to completion and supports cancellable indeterminate work', async ({page}) => {
  const section = page.locator('#progress')
  const experience = section.getByRole('progressbar', {name: 'Experience'})
  const earn = section.getByRole('button', {name: 'Earn 20 XP'})
  await expect(experience).toHaveAttribute('aria-valuenow', '40')
  await earn.click()
  await expect(experience).toHaveAttribute('aria-valuenow', '60')
  await earn.click()
  await earn.click()
  await expect(experience).toHaveAttribute('aria-valuenow', '100')
  await expect(earn).toBeDisabled()
  await section.getByRole('button', {name: 'Reset XP'}).click()
  await expect(experience).toHaveAttribute('aria-valuenow', '0')
  await expect(earn).toBeEnabled()
  await section.getByRole('button', {name: 'Find a party'}).click()
  const search = section.getByRole('progressbar', {name: 'Finding a party'})
  await expect(search).not.toHaveAttribute('aria-valuenow')
  await expect(section.getByRole('status').filter({hasText: 'Searching for adventurers'})).toHaveText('Searching for adventurers…')
  await section.getByRole('button', {name: 'Cancel search'}).click()
  await expect(search).toHaveAttribute('aria-valuenow', '100')
  await expect(section).toHaveScreenshot('quest-progress.png')
})

test('skeleton respects reduced motion and gives way to the loaded profile', async ({page}) => {
  await page.emulateMedia({reducedMotion: 'reduce'})
  const section = page.locator('#skeleton')
  const profile = section.getByRole('region', {name: 'Adventurer profile'})
  await expect(profile).toHaveAttribute('aria-busy', 'true')
  const placeholders = profile.locator('[aria-hidden="true"]')
  await expect(placeholders).toHaveCount(3)
  for (const placeholder of await placeholders.all()) {
    await expect(placeholder).toHaveCSS('animation-name', 'none')
  }
  await expect(section).toHaveScreenshot('quest-skeleton-reduced-motion.png')
  await section.getByRole('button', {name: 'Reveal profile'}).click()
  await expect(profile).toHaveAttribute('aria-busy', 'false')
  await expect(profile.getByRole('heading', {name: 'Rowan the Brave'})).toBeVisible()
  await expect(placeholders).toHaveCount(0)
  await section.getByRole('button', {name: 'Load profile again'}).click()
  await expect(profile).toHaveAttribute('aria-busy', 'true')
  await expect(placeholders).toHaveCount(3)
})
