import {expect, test} from '@playwright/test'

test.beforeEach(async ({page}) => {
  await page.goto('/demo')
  await page.evaluate(() => document.fonts.ready)
})

test('confirmation cancellation leaves the expedition active and confirmation changes it', async ({page}) => {
  const section = page.locator('#overlays-extra')
  const trigger = section.getByRole('button', {name: 'Abandon expedition', exact: true})
  await trigger.click()
  const dialog = page.getByRole('alertdialog', {name: 'Abandon this expedition?'})
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button', {name: 'Keep exploring'})).toBeFocused()
  await dialog.getByRole('button', {name: 'Keep exploring'}).click()
  await expect(dialog).toBeHidden()
  await expect(trigger).toBeFocused()
  await expect(section.getByText('Expedition is active.', {exact: true})).toBeVisible()
  await trigger.click()
  await dialog.getByRole('button', {name: 'Confirm abandonment'}).click()
  await expect(dialog).toBeHidden()
  await expect(section.getByText('Expedition abandoned.', {exact: true})).toBeVisible()
})

test('side sheet stays attached to the viewport and restores focus after Escape', async ({page}) => {
  const trigger = page.locator('#overlays-extra').getByRole('button', {name: 'Open quest sheet'})
  await trigger.click()
  const sheet = page.getByRole('dialog', {name: 'Quest details'})
  await expect(sheet).toBeVisible()
  const bounds = await sheet.boundingBox()
  const viewport = page.viewportSize()
  if (!bounds || !viewport) throw new Error('Expected sheet and viewport bounds')
  expect(Math.abs(bounds.x + bounds.width - viewport.width)).toBeLessThanOrEqual(1)
  await page.keyboard.press('Escape')
  await expect(sheet).toBeHidden()
  await expect(trigger).toBeFocused()
})

test('drawer dismisses with Escape or an explicit supply action and restores its trigger', async ({page}) => {
  const section = page.locator('#overlays-extra')
  const trigger = section.getByRole('button', {name: 'Open supply drawer'})
  await trigger.click()
  const drawer = page.getByRole('dialog', {name: 'Expedition supplies'})
  await expect(drawer).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(drawer).toBeHidden()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await drawer.getByRole('button', {name: 'Take supplies'}).click()
  await expect(drawer).toBeHidden()
  await expect(section.getByText('Supplies collected.', {exact: true})).toBeVisible()
})

test('two independent disclosures keep their own expansion states', async ({page}) => {
  const section = page.locator('#overlays-extra')
  const notes = section.getByRole('button', {name: 'Expedition notes'})
  const companion = section.getByRole('button', {name: 'Companion notes'})
  await notes.focus()
  await page.keyboard.press('Enter')
  await companion.focus()
  await page.keyboard.press('Space')
  await expect(notes).toHaveAttribute('aria-expanded', 'true')
  await expect(companion).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('Space')
  await expect(companion).toHaveAttribute('aria-expanded', 'false')
  await expect(section.getByText('The eastern gate opens at sunrise.')).toBeVisible()
})

test('command search filters results and keyboard selection performs the chosen action', async ({page}) => {
  const section = page.locator('#overlays-extra')
  const trigger = section.getByRole('button', {name: 'Find expedition command'})
  await trigger.click()
  const dialog = page.getByRole('dialog', {name: 'Expedition commands'})
  const search = dialog.getByRole('combobox', {name: 'Search expedition commands'})
  await expect(search).toBeFocused()
  await search.fill('missing')
  await expect(dialog.getByText('No expedition commands found.')).toBeVisible()
  await search.fill('camp')
  await expect(dialog.getByRole('option', {name: 'Return to camp'})).toBeVisible()
  await expect(dialog.getByRole('option', {name: 'Open world map'})).toHaveCount(0)
  await search.press('ArrowDown')
  await search.press('Enter')
  await expect(dialog).toBeHidden()
  await expect(section.getByText('Command selected: camp.', {exact: true})).toBeVisible()
  await expect(trigger).toBeFocused()
})

test('menubar arrows reach multiple real menus and checkbox state persists', async ({page}) => {
  const section = page.locator('#overlays-extra')
  const toolbar = section.getByRole('toolbar', {name: 'Expedition menu'})
  await toolbar.getByRole('button', {name: 'Expedition', exact: true}).focus()
  await page.keyboard.press('ArrowRight')
  await expect(toolbar.getByRole('button', {name: 'Map view'})).toBeFocused()
  await page.keyboard.press('ArrowDown')
  const grid = page.getByRole('menuitemcheckbox', {name: 'Show grid'})
  await expect(grid).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(grid).toHaveAttribute('aria-checked', 'true')
  await page.keyboard.press('Escape')
  await expect(toolbar.getByRole('button', {name: 'Map view'})).toBeFocused()
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(section.getByText('Checkpoint saved. Grid visible.', {exact: true})).toBeVisible()
})

for (const theme of ['overworld', 'castle'] as const) {
  test(`extra overlay pixel frames in ${theme}`, async ({page}) => {
    if (theme === 'castle') await page.getByRole('button', {name: 'Switch to Castle', exact: true}).click()
    const section = page.locator('#overlays-extra')
    await section.getByRole('button', {name: 'Expedition notes'}).click()
    await expect(section).toHaveScreenshot(`overlays-extra-${theme}.png`)
    await section.getByRole('button', {name: 'Abandon expedition', exact: true}).click()
    await expect(page.getByRole('alertdialog')).toHaveScreenshot(`alert-dialog-${theme}.png`)
    await page.keyboard.press('Escape')
    await section.getByRole('button', {name: 'Open quest sheet'}).click()
    await expect(page.getByRole('dialog', {name: 'Quest details'})).toHaveScreenshot(`sheet-${theme}.png`)
    await page.keyboard.press('Escape')
    await section.getByRole('button', {name: 'Open supply drawer'}).click()
    await expect(page.getByRole('dialog', {name: 'Expedition supplies'})).toHaveScreenshot(`drawer-${theme}.png`)
    await page.keyboard.press('Escape')
    await section.getByRole('button', {name: 'Find expedition command'}).click()
    await expect(page.getByRole('option', {name: 'Open world map'})).toBeVisible()
    await expect(page.getByRole('dialog', {name: 'Expedition commands'})).toHaveScreenshot(`command-${theme}.png`)
    await page.keyboard.press('Escape')
    await section.getByRole('button', {name: 'Map view'}).click()
    await expect(page.getByRole('menu')).toHaveScreenshot(`menubar-menu-${theme}.png`)
  })
}

test('forced colors and reduced motion preserve accessible overlay controls', async ({page}) => {
  await page.emulateMedia({forcedColors: 'active', reducedMotion: 'reduce'})
  const section = page.locator('#overlays-extra')
  await section.getByRole('button', {name: 'Open quest sheet'}).click()
  const sheet = page.getByRole('dialog', {name: 'Quest details'})
  await expect(sheet).toHaveScreenshot('sheet-forced-colors.png')
  await sheet.getByRole('button', {name: 'Close quest sheet'}).click()
  await expect(sheet).toBeHidden()
})
